### ISSUE TITLE
Changing `X` to `(false ? ... : X)` leads to black image

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#12]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nvidia-shield-tv/wrong_images/large-v100-0e912d54531ac00b_inv_variant_82) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nvidia-shield-tv/wrong_images/large-v100-0e912d54531ac00b_inv_variant_82)

WebGL links for reproduction:

* [Recipient](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/nvidia-shield-tv/wrong_images/large-v100-0e912d54531ac00b_inv_variant_82/webgl_viewer_recipient.html)
* [Variant](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/nvidia-shield-tv/wrong_images/large-v100-0e912d54531ac00b_inv_variant_82/webgl_viewer_variant.html)

The variant shader has the following small change vs. the recipient shader: 

* Each expression `X` surrounded by `/**/` in the function below is changed to `(false ? (--s) : X)`. This leads to a black image.

```glsl
vec3 hsbToRGB(float h, float s, float b)
{
    return 
    b 
    * 
    ( /**/(1.0)/**/ - s)
    + 
    (b - /**/(b * (1.0 - s))/**/ )
    * 
    clamp
    (
      abs(abs( /**/(6.0)/**/ * (h - vec3(0, 1, 2) / 3.0)) - 3.0) 
      - 
      1.0
      , 
      0.0
      , 
      1.0
    );
}
```

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/nvidia-shield-tv/wrong_images/large-v100-0e912d54531ac00b_inv_variant_82/recipient_reduced_final_manual.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/nvidia-shield-tv/wrong_images/large-v100-0e912d54531ac00b_inv_variant_82/variant_82_reduced_final_manual.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://devtalk.nvidia.com/default/topic/978569/opengl-es/-bug-glsl-compiler-bug-changing-expression-x-to-false-x-leads-to-black-image/

**Comment by afd** [comment]
NVIDIA told us by email that all the Shield issues we reported have been fixed and that the fixes are in the latest system updates; we should confirm the fix.

**Comment by paulthomson** [comment]
We confirmed this was fixed. Version: 5.2(24.28.403.127)
