### ISSUE TITLE
Compiler issues invalid error: non constant expression in initialization

### ISSUE THREAD

**Issue by afd** [mc-imperial/shader-compiler-bugs#13]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-Windows10/compile_fail/large-v440-028011ce6441692b_inv_variant_43) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-Windows10/compile_fail/large-v440-028011ce6441692b_inv_variant_43)

This code:

```
#version 440

void main(void)
{
  vec4 A[2] = vec4[2](vec4(1.0), vec4((vec2(1.0) * mat2(1.0)).x));
  int x = 1;
  vec4 y = vec4(A[x].z);
}
```

is accepted by glslangValidator (and also a recent Intel driver).

The NVIDIA compiler erroneously gives an error:

```
LINK_ERROR
Vertex info
-----------
0(2) : warning C7555: 'attribute' is deprecated, use 'in/out' instead

Fragment info
-------------
0(7) : error C1059: non constant expression in initialization
```

**Comment by afd** [comment]
Filed bug report to NVIDIA:

https://devtalk.nvidia.com/default/topic/978833/opengl/-bug-compile-error-quot-non-constant-expression-in-initialization-quot-/

**Comment by 0152la** [comment]
Shader now compiles successfully in driver version 378.66.
