### ISSUE TITLE
Compiler issues error: "too little data in type constructor" and then a fatal error

### ISSUE THREAD

**Issue by afd** [mc-imperial/shader-compiler-bugs#14]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-Windows10/compile_fail/large-v440-028011ce6441692b_inv_variant_80) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-Windows10/compile_fail/large-v440-028011ce6441692b_inv_variant_80)

This code:

```
#version 440

float foo(out vec3 p)
{
    for(int c = 0; c < 6; ++ c) {
        p = abs(p) +
            vec3(1.0,
                 (false ? 1.0 : (false ? distance(1.0, 1.0) : 1.0)) + (true ? 0.1 : length(vec3(1.0))),
                 (true ? 1.0 : 1.0 - step(1.0, 1.0)) + 0.3
            );
    }
    return 1.0;
}
void main(void)
{
   vec3 v;
   foo(v);
}
```

is accepted by glslangValidator (and also a recent Intel driver).

The NVIDIA compiler gives a fatal error:

```
Fragment info
-------------
0(17) : error C1067: too little data in type constructor
0(17) : error C1067: too little data in type constructor
(0) : fatal error C9999: Can't convert to expr: 1, @TMP3 + 0.1f
```

**Comment by afd** [comment]
Filed to NVIDIA:

https://devtalk.nvidia.com/default/topic/978834/opengl/-bug-error-quot-too-little-data-in-type-constructor-quot-and-then-fatal-error/

**Comment by 0152la** [comment]
Shader now compiles successfully in driver version 378.66.
