### ISSUE TITLE
Adding 0.0 to an expression leads to significantly different image

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#27]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/htc-one-m7/wrong_images/large-v100-ec79d13f501f1cd8_inv_variant_84) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/htc-one-m7/wrong_images/large-v100-ec79d13f501f1cd8_inv_variant_84)

These shaders should render a space scene image.
See the `actual.png` rendered on my Intel GPU:

![intel image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/htc-one-m7/wrong_images/large-v100-ec79d13f501f1cd8_inv_variant_84/expected.png "intel image")

 But the HTC One M7 renders a red image. In addition, the small change (effectively adding `+ 0.0`) described at the link above changes the image to be black.

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/htc-one-m7/wrong_images/large-v100-ec79d13f501f1cd8_inv_variant_84/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/htc-one-m7/wrong_images/large-v100-ec79d13f501f1cd8_inv_variant_84/variant_84_reduced_final_manual.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://developer.qualcomm.com/forum/qdn-forums/software/adreno-gpu-sdk/33679

**Comment by mikk150** [comment]
![2017-02-25 13 49 55](https://cloud.githubusercontent.com/assets/4953629/23331624/65bc867e-fb72-11e6-8722-d5bad662144e.jpg)
Is this considered a bug?
Adreno 418

**Comment by afd** [comment]
It's hard to say: this shader seems to be really floating-point sensitive.  We're wondering whether the adding of zero changes what precision qualifiers do here and whether that changes the image.  If you change mediump to highp in the shader, does the issue go away?  (If it doesn't, this adds evidence to this perhaps being just a floating-point issue, though it could still be a bug nevertheless.)
