### ISSUE TITLE
Metamorphic transformation leads to WebGL blue-screen

### ISSUE THREAD

**Issue by 0152la** [mc-imperial/shader-compiler-bugs#28]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Fury-WebGL-ANGLE/crashes/large-v100-webgl-241618d7c4457924) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Fury-WebGL-ANGLE/crashes/large-v100-webgl-241618d7c4457924)

Device: AMD R9 Fury
Windows 10 driver version: 16.9.2

Comparison of observed effects available [here](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/AMD-R9-Fury-WebGL-ANGLE/crashes/large-v100-webgl-241618d7c4457924/note).

**Comment by 0152la** [comment]
AMD Report Form ("n/a" means not filled):

Graphics Card Model:
	Radeon R9 Fury X
	
Graphics Card Part Number:
	n/a
	
AMD Radeon Software Driver Version:
	AMD Radeon Software Crimson Edition 16.9.2
	
Driver History:
	Do Not Know
	
Operating System:
	Windows 10 64-bit
	
Type of Issue:
	Other
	
Crossfire Configuration: 
	No
	
Using Mantle: 
	No
	
Other Games/Applications: 
	Google Chrome
	
Describe the Issue and Steps to replicate:
	We use a custom written WebGL launcher and Chrome (self-contained HTML available for download at [1]; paste the shader code in the top box and hit "Execute"). When rendering the shader via WebGL, the device driver crashes. A number of things might happen:
	* The browser continues fine, with the "Rats! WebGL hit a snag!" message
	* The browser hangs, with the ability to force-close it
	* The machine blue-screens, with the "THREAD_STUCK_IN_DEVICE_DRIVER" error

	The effects are more deterministic with an ANGLE-based binary (source available for download at [2]). On our machine, we can reproduce the blue-screen consistently upon the first attempt at rendering the shader.

	The shaders we used are available to see at [3]. Additionally, the problematic shader is available for download at [4].

	[1] http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/utils/webgl/webgl_viewer.html
	[2] https://github.com/paulthomson/GetImageAngle
	[3] https://github.com/mc-imperial/shader-compiler-bugs/issues/28
	[4] <LINK_REMOVED>
	
CPU Details:
	Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz, 3701 Mhz, 4 Core(s), 8 Logical Processor(s)

Display Devices and Connections used:
	Dell S2009W on HDMI
	
Motherboard or System Make & Model:
	n/a

Motherboard BIOS version:
	n/a
	
System Memory Type & Amount:
	32GB
	
Power Supply Wattage:
	n/a

**Comment by afd** [comment]
AMD fixed this in driver version 17.1.1.
