### ISSUE TITLE
fatal error C9999: unexpected expression in DUI_foreachId

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#3]
[[Shaders, screenshots, error log, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nvidia-shield-tv/link_errors/large-v100-0c1c53fe70b4943b_inv_variant_71) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nvidia-shield-tv/link_errors/large-v100-0c1c53fe70b4943b_inv_variant_71)

variant_71_reduced_final_manual.frag:

```glsl
#version 100

#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 injectionSwitch;

void main()
{
    for(int r = 0; r < 6; r ++)
    {
        vec3 dir = vec3(injectionSwitch, 1.);
        dir.xz *= mat2(1.0);
    }
}
```

Link error log:

```
Fragment info
-------------
(0) : fatal error C9999: unexpected expression in DUI_foreachId
```

**Comment by paulthomson** [comment]
Reported: https://devtalk.nvidia.com/default/topic/977912/opengl-es/-bug-glsl-link-error-for-valid-shader-quot-fatal-error-c9999-unexpected-expression-in-dui_foreachid-quot-/

**Comment by paulthomson** [comment]
We confirmed this was fixed. Version: 5.2(24.28.403.127)

**Comment by afd** [comment]
Changing link-error to compile-error to keep things simple.
