### ISSUE TITLE
Adding an empty if statement and other changes causes rendered "worm" to disappear

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#36]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/iphone-se-webgl/wrong_images/large-v100-webgl-d404d67b44f886a3_inv_variant_5) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/iphone-se-webgl/wrong_images/large-v100-webgl-d404d67b44f886a3_inv_variant_5)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/iphone-se-webgl/wrong_images/large-v100-webgl-d404d67b44f886a3_inv_variant_5/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/iphone-se-webgl/wrong_images/large-v100-webgl-d404d67b44f886a3_inv_variant_5/variant_5_reduced_final_manual.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://community.imgtec.com/forums/topic/bug-glsl-iphone-se-empty-if-statement-in-shader-gives-incorrect-image/

**Comment by paulthomson** [comment]
Also reported to Apple. Bug report ID: 29478612

**Comment by paulthomson** [comment]
ImgTech say they could not reproduce on Android and that the iPhone drivers are written by Apple.

**Comment by afd** [comment]
Apple confirmed this issue, as did many Twitter users in response to this tweet:

https://twitter.com/afd_icl/status/806786247595175936

Apple reported by email that they subsequently fixed the issue.
