### ISSUE TITLE
Wrapping code in a single-iteration loop changes the rendered image

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#50]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nexus-player/wrong_images/large-v100-6a34d929ab771b65_inv_variant_25) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nexus-player/wrong_images/large-v100-6a34d929ab771b65_inv_variant_25)

WebGL links for easy reproduction:

* [Recipient](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/nexus-player/wrong_images/large-v100-6a34d929ab771b65_inv_variant_25/webgl_viewer_recipient.html)
* [Variant](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/nexus-player/wrong_images/large-v100-6a34d929ab771b65_inv_variant_25/webgl_viewer_variant.html)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/nexus-player/wrong_images/large-v100-6a34d929ab771b65_inv_variant_25/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/nexus-player/wrong_images/large-v100-6a34d929ab771b65_inv_variant_25/variant_25_reduced_final.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://community.imgtec.com/forums/topic/bug-glsl-nexus-player-single-iteration-loop-changes-the-rendered-image/

**Comment by paulthomson** [comment]
ImgTech say they could not reproduce on their newer, internal drivers.

**Comment by afd** [comment]
Closing this issue as Imagination reported that it doesn't manifest on their newer drivers, so likely independently fixed.
