### ISSUE TITLE
Multiplication by 1 and addition with 0 leads to different image

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#55]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/samsung-galaxy-s6/wrong_images/large-v100-5647937ed5c44a1a_inv_variant_13) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/samsung-galaxy-s6/wrong_images/large-v100-5647937ed5c44a1a_inv_variant_13)

WebGL links for easy reproduction:

* [Recipient](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/samsung-galaxy-s6/wrong_images/large-v100-5647937ed5c44a1a_inv_variant_13/webgl_viewer_recipient.html)
* [Variant](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/samsung-galaxy-s6/wrong_images/large-v100-5647937ed5c44a1a_inv_variant_13/webgl_viewer_variant.html)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/samsung-galaxy-s6/wrong_images/large-v100-5647937ed5c44a1a_inv_variant_13/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/samsung-galaxy-s6/wrong_images/large-v100-5647937ed5c44a1a_inv_variant_13/variant_13_reduced_final.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://www.community.arm.com/graphics/f/discussions/51/bug-glsl-samsung-galaxy-s6-multiplication-by-1-and-addition-with-0-leads-to-different-image

**Comment by Cristallix** [comment]
You got an answer about this bug. Peter Harris said :

> Hi Paul,
> 
> Our compiler team has been investigating this one and we've come to the conclusion that we don't think this is a bug. The error occurs because the shader is using some "mediump" variables which seem to be relying on getting higher precision than the "mediump" specification minimums actually guarantee. We've observed instances of fp16 variables overflowing and hitting a +INF condition.
> 
> The additional logic added in your test case means the compiler optimizes the code differently (the ESSL specification is relatively relaxed compared to C with regards to reassociation of variables) which causes the bug to trigger. If we force shader precision to "highp" the render works as expected as you avoid the infinity overflows.
> 
> Regards,
> Pete
