### ISSUE TITLE
Wrapping code in ternary operator with macro declaration leads to compilation failure

### ISSUE THREAD

**Issue by 0152la** [mc-imperial/shader-compiler-bugs#58]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-24afbaa352c7190c_inv_variant_84) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-24afbaa352c7190c_inv_variant_84)

The line:

`backCol2 += mix(.4, 1., v2) * vec3(1.8 * t3 * t3 * t3, 1.4 * t3 * t3, t3) * fade;`

becomes:

`backCol2 += mix(.4, 1., v2) * vec3((injectionSwitch.x < injectionSwitch.y ? 1.8 * t3 * t3 * t3 : GLF_live1pi), 1.4 * t3 * t3, t3) * fade;`

Tested on Chrome and Firefox, verified with glslangValidator. OpenGL renders the image correctly.

Might be related to #57, as they both make use of macros.

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-24afbaa352c7190c_inv_variant_84/original.png "recipient image")

Variant:

[Compilation output](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-24afbaa352c7190c_inv_variant_84/variant.txt)

**Comment by 0152la** [comment]
Reported:

https://devtalk.nvidia.com/default/topic/982345/opengl/-bug-webgl-wrapping-code-in-ternary-operator-with-macro-declaration-leads-to-compilation-failure/

**Comment by paulthomson** [comment]
I can repro this on my MacBook Pro (Intel) Windows 10 Chrome. But not on Edge. I guess this is an ANGLE bug. We should report to them.

**Comment by 0152la** [comment]
Again similar to #57, after updating drivers to 378.66, the shader is now correctly rendered in Chrome, but not in Firefox. Firefox issues the same "redefinition" error as observed above.

**Comment by afd** [comment]
Re-labelled as angle, and now closing.  Remains "reported", even though we didn't report it to ANGLE.

**Comment by 0152la** [comment]
Tested on Firefox 54.0.1 and Chrome 59.0.3071.115 and could not reproduce the issue.
