### ISSUE TITLE
Adding a single, meaningless if-else to a shader source leads to different image

### ISSUE THREAD

**Issue by hevrard** [mc-imperial/shader-compiler-bugs#62]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6/original.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6/variant.png "variant image")

**Comment by hevrard** [comment]
Reported to Mesa: https://bugs.freedesktop.org/show_bug.cgi?id=100303

**Comment by afd** [comment]
The issue is reported to be fixed by Mesa folks.
