### ISSUE TITLE
ANGLE gives internal error

### ISSUE THREAD

**Issue by afd** [mc-imperial/shader-compiler-bugs#63]
With Google Chrome Version 57.0.2987.110 (64-bit), ANGLE gives an internal error when applied to this shader:

https://github.com/mc-imperial/shader-compiler-bugs/blob/master/angle/front-end/internal-error/shader.frag

Here is the error string:

Failed to link shader program.
C:\fakepath(29,56-76): internal error: invalid access of unbound variable

Warning: D3D shader compilation failed with default flags. (ps_5_0)
 Retrying with skip validation
C:\fakepath(29,56-76): internal error: invalid access of unbound variable

Warning: D3D shader compilation failed with skip validation flags. (ps_5_0)
 Retrying with skip optimization
C:\fakepath(29,56-76): internal error: invalid access of unbound variable

Warning: D3D shader compilation failed with skip optimization flags. (ps_5_0)
Failed to create D3D shaders.

**Comment by afd** [comment]
Reported to ANGLE here:

https://bugs.chromium.org/p/angleproject/issues/detail?id=1945

**Comment by afd** [comment]
The issue comments indicate that this is an HLSL compiler bug.

**Comment by hevrard** [comment]
As of 8 Jan 2018, the fix is available in Windows Insider:
https://bugs.chromium.org/p/angleproject/issues/detail?id=1945#c6
