### ISSUE TITLE
Adding unreachable "return" and "continue" in a GLSL shader leads to different image

### ISSUE THREAD

**Issue by hevrard** [mc-imperial/shader-compiler-bugs#70]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/large-v100-197d922443aac5da_inv_variant_48) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/large-v100-197d922443aac5da_inv_variant_48)

Difference between the two shaders (the injectionSwitch uniform is set such that the condition "(injectionSwitch.x > injectionSwitch.y)" is always false):
```
27a28,29
> uniform vec2 injectionSwitch;
>
33a36,39
>     if(injectionSwitch.x > injectionSwitch.y)
>         {
>             return vec2(1.0);
>         }
120a127
>     c = c;
202a210,213
>                     if(injectionSwitch.x > injectionSwitch.y)
>                         {
>                             continue;
>                         }
```

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/large-v100-197d922443aac5da_inv_variant_48/original.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/large-v100-197d922443aac5da_inv_variant_48/variant.png "variant image")

**Comment by hevrard** [comment]
Reported: https://bugs.freedesktop.org/show_bug.cgi?id=100580

**Comment by afd** [comment]
Closing as Mesa closed it as not being reproducible on their latest drivers.
