### ISSUE TITLE
swiftshader rendering does not terminate

### ISSUE THREAD

**Issue by afd** [mc-imperial/shader-compiler-bugs#73]
What steps will reproduce the problem?

[original.frag](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/swift-shader/wrong-code/infinite_loop/original.frag) produces image [original.png](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/swift-shader/wrong-code/infinite_loop/original.png).  [variant.frag](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/swift-shader/wrong-code/infinite_loop/variant.frag) should produce the same image, because variant.frag and original.frag are identical except that in variant.frag some statements are wrapped in single-iteration "for" loops.

This was tested with get-image-egl (https://github.com/graphicsfuzz/get-image-egl) with LD_LIBRARY_PATH set to a swiftshader build directory, but it is likely that any other way of compiling the shader will produce the same problem.

The steps to produce it with get-image-egl are:

1. Download or build an appropriate binary for get_image (this was tested on https://github.com/graphicsfuzz/get-image-egl/releases/tag/v-936f0d26452d3c52a0b8552be77cc6798f99bcd7 but is unlikely to be version specific)
2. export LD_LIBRARY_PATH=/path/to/swiftshader/libraries.
3. Run get_image <name>.frag

A rendered image should then appear as <name>.png.

What is the expected output?

Both "original.frag" and "variant.frag" should produce "original.png"

What do you see instead?

I find that rendering of "variant.frag" does not complete.  On one occasion I found that rendering aborted with the error shown in [error.txt](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/swift-shader/wrong-code/infinite_loop/error.txt), but I could not reproduce this - all other executions led to a hang.

What version of the product are you using? On what operating system?

This was tested on swiftshader built from commit b89010f built with "cmake -DCMAKE_BUILD_TYPE=Release".

The operating system is Windows 10.

**Comment by afd** [comment]
[Reported upstream](https://bugs.chromium.org/p/swiftshader/issues/detail?id=55)

**Comment by afd** [comment]
The issue is marked as "started", so regarding this as confirmed.

**Comment by c0d1f1ed** [comment]
SwiftShader is deprecating its legacy OpenGL ES front-end, to be replaced by using ANGLE on top of the SwiftShader Vulkan implementation (aka. SwANGLE).

I'll close https://bugs.chromium.org/p/swiftshader/issues/detail?id=55 but if this is still relevant and reproduces with SwANGLE, please file a bug at https://issuetracker.google.com/issues?q=componentid:706646

**Comment by paulthomson** [comment]
Thanks!
