### ISSUE TITLE
Adding a single-iteration do-while loop in a GLSL shader leads to a different image

### ISSUE THREAD

**Issue by hevrard** [mc-imperial/shader-compiler-bugs#75]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/Intel-i7-2600-Mesa-Linux/wrong_images/18May_130_noliterals_colorgrid_modulo_inv_variant_2) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/Intel-i7-2600-Mesa-Linux/wrong_images/18May_130_noliterals_colorgrid_modulo_inv_variant_2)

Diff:
```
--- original.frag	2017-06-28 11:04:21.278754777 +0100
+++ variant.frag	2017-06-28 11:23:16.925591708 +0100
@@ -42,10 +42,12 @@
                 {
                     s += _FLOAT_CONST[2];
                 }
+            do {
             if(float(i) >= limit)
                 {
                     return s;
                 }
+            } while(gl_FragCoord.x < 0.0);
         }
     return s;
 }
```

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/Intel-i7-2600-Mesa-Linux/wrong_images/18May_130_noliterals_colorgrid_modulo_inv_variant_2/original.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/Intel-i7-2600-Mesa-Linux/wrong_images/18May_130_noliterals_colorgrid_modulo_inv_variant_2/variant.png "variant image")

**Comment by hevrard** [comment]
reported here:
https://bugs.freedesktop.org/show_bug.cgi?id=101648

**Comment by afd** [comment]
Marked as FIXED by Ilia Mirkin 2018-06-05 13:38:59 UTC
