### ISSUE TITLE
Constant foldable expression with assignment from literal of different type crashes Intel Mesa compiler

### ISSUE THREAD

**Issue by DRMacIver** [mc-imperial/shader-compiler-bugs#78]
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/Intel-i7-2600-Mesa-Linux/crashes//invalid_type) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/Intel-i7-2600-Mesa-Linux/crashes/invalid_type)

This crashes with:

```
glsl/ir_expression_operation_constant.h:228: virtual ir_constant* ir_expression::constant_expression_value(hash_table*): Assertion `!"invalid type"' failed
```

**Comment by DRMacIver** [comment]
I can reproduce this with just `glsl_compiler` built from master, so I will report it upstream on that basis.

**Comment by hevrard** [comment]
On 12/07/17 15:51, David R. MacIver wrote:
> I can reproduce this with just |glsl_compiler| built from master, so I
> will report it upstream on that basis.

Sounds good!

Thanks,
Hugues

**Comment by DRMacIver** [comment]
[I have now reported this upstream](https://bugs.freedesktop.org/show_bug.cgi?id=101766).

**Comment by DRMacIver** [comment]
Fixed upstream as of early this morning.
