### ISSUE TITLE
Dead code causes flickering rectangle to be drawn (image should be static)

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#9]
[[Shaders, screenshots, error log, reproduction steps, platform details, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/htc-one-m7/wrong_images/large-v100-1f45b3419197dd6a_inv_variant_43) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/htc-one-m7/wrong_images/large-v100-1f45b3419197dd6a_inv_variant_43)

Recipient:

![recipient image](https://raw.githubusercontent.com/mc-imperial/shader-compiler-bugs/master/htc-one-m7/wrong_images/large-v100-1f45b3419197dd6a_inv_variant_43/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://raw.githubusercontent.com/mc-imperial/shader-compiler-bugs/master/htc-one-m7/wrong_images/large-v100-1f45b3419197dd6a_inv_variant_43/variant_43_m_reduced_250_simplified_m.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://developer.qualcomm.com/forum/qdn-forums/software/adreno-gpu-sdk/33665

**Comment by afd** [comment]
Qualcomm indicated during email conversations that they are not supporting the HTC One M7 anymore.  So should we close this issue, indicating that it won't be fixed?
